

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'd6d25316-9eb8-4578-8354-2e7fa463687b'
    definition: '24'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    allowFailedBuilds: true
    targetPath: '$(Pipeline.Workspace)'
